change key path to SNOWFLAKE_PRIVATE_KEY
flyteorg/flytekit pull request #1879
Opened 2023-10-06 14:54 UTC by hhcs9527

# TL;DR
change key path to SNOWFLAKE_PRIVATE_KEY

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Tracking Issue
[Flyte Agent Ecosystem](https://github.com/flyteorg/flyte/issues/3936)

2023-10-06 21:01 UTC, pingsutw approved these changes

2023-10-06 21:01 UTC, pingsutw requested changes
There is a linting error

2023-10-07 02:13 UTC, hhcs9527 commented
hi @pingsutw , fix the lint error

2023-10-09 18:08 UTC, pingsutw approved these changes

2023-10-09 18:15 UTC, pingsutw approved these changes

2023-10-09 19:08 UTC, merged